language: java
jdk:
- openjdk8
os:
- linux
cache:
  directories:
  - ~/.m2/repository
env:
- MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.codehaus.mojo.cobertura.CoberturaReportMojo=off
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Djib.skip -q -Ptravis
script:
- mvn test -B -Djib.skip -q cobertura:cobertura coveralls:report -Ptravis -DrepoToken=${COVERALLS_REPO_TOKEN}
